nutzam/nutz

- src/org/nutz/castor/castor/String2Enum.java
- test/org/nutz/castor/AlipayNotifyType.java
- test/org/nutz/castor/CastorTest.java
```
public enum AlipayNotifyType {
StatusSync("trade_status_sync");
private String state;
private AlipayNotifyType(String s) {
state = s;
}
@Override
public String toString() {
return state;
}
}
```
> 增加String2Enum对名、值不同的枚举的支持。

- src/org/nutz/dao/impl/NutDao.java
原有的实现使用Pojo的after钩子来实现, 现在改成用Dao原有的query方法实现,这样就实现了缓存友好. 因为缓存是根据sql缓存
> 改造dao.fetchLinks,使用普通的query方法实现查询,使其缓存友好

- src/org/nutz/castor/castor/Map2String.java
- src/org/nutz/castor/castor/Object2String.java
- src/org/nutz/dao/entity/annotation/ColType.java
- src/org/nutz/dao/impl/jdbc/psql/PsqlArrayAdaptor.java
- src/org/nutz/dao/impl/jdbc/psql/PsqlJdbcExpert.java
- src/org/nutz/dao/impl/jdbc/psql/PsqlJsonAdaptor.java
- test/org/nutz/dao/AllDao.java
- test/org/nutz/dao/test/normal/psql/Psql.java
- test/org/nutz/dao/test/normal/psql/PsqlArrayTest.java
- test/org/nutz/dao/test/normal/psql/PsqlJsonTest.java
- test/org/nutz/dao/test/normal/psql/Student.java
- test/org/nutz/dao/test/normal/psql/StudentArray.java
- test/org/nutz/dao/test/normal/psql/StudentJson.java
- test/org/nutz/dao/test/normal/psql/StudentResult.java
1）PsqlJsonAdaptor 只解决了使用 POJO 的情况，用 Chain 来操作的话还未解决，#921
2）使用数组的时候需要 POJO 实现`带一个参数的静态工厂方法`或者`带一个参数的构造函数`，不然无法把数据库字段的值映射到 POJO 的字段中
> 添加两个 Adaptor 类让更方便的使用 PostgreSQL 数据库

- src/org/nutz/aop/ClassAgent.java
- src/org/nutz/aop/DefaultClassDefiner.java
- src/org/nutz/aop/InterceptorChain.java
- test/org/nutz/lang/reflect/FastClassFactoryTest.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1213 The members of an interface declaration or class should appear in a pre-defined order,
squid:S00105 Tabulation characters should not be used,
squid:S3008 Static non-final field names should comply with a naming convention,
squid:S1197 Array designators "[]" should be on the type, not the variable
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1213
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00105
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS3008
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1197
George Kankava
> multiple code improvements: squid:S1213, squid:S00105, squid:S3008, squid:S1197

- src/org/nutz/dao/Chain.java
- src/org/nutz/dao/FieldMatcher.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1066 - Collapsible "if" statements should be merged.
squid:S00122 - Statements should be on separate lines.
https://dev.eclipse.org/sonar/rules/show/squid:S1066
https://dev.eclipse.org/sonar/rules/show/squid:S00122
George Kankava
> Multiple code improvements - squid:S1066, squid:S00122

- src/org/nutz/aop/asm/AopMethodAdapter.java
- src/org/nutz/aop/asm/AsmClassAgent.java
- src/org/nutz/aop/asm/AsmHelper.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1192 - String literals should not be duplicated.
squid:CommentedOutCodeLine - Sections of code should not be "commented out".
https://dev.eclipse.org/sonar/rules/show/squid:S1192
https://dev.eclipse.org/sonar/rules/show/squid:CommentedOutCodeLine
George Kankava
> Multiple code improvements - squid:S1192, squid:CommentedOutCodeLine

- src/org/nutz/aop/AbstractClassAgent.java
- src/org/nutz/aop/asm/AsmClassAgent.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1213 The members of an interface declaration or class should appear in a pre-defined order,
squid:ClassVariableVisibilityCheck Class variable fields should not have public accessibility,
squid:S1155 Collection.isEmpty() should be used to test for emptiness,
squid:S00117 Local variable and method parameter names should comply with a naming convention,
squid:S1125 Literal boolean values should not be used in condition expressions,
squid:S1319 Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList".
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1213 …
> multiple code improvements: squid:S1213, squid:ClassVariableVisibilityCheck, squid:S1155, squid:S00117, squid:S1125, squid:S1319

- src/org/nutz/dao/util/Daos.java
Fix: ORA-00933: SQL 命令未正确结束
2016-7-12 17:9:31.172 DEBUG [main] Database info --> ORACLE:[Oracle - Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options]
...
2016-7-12 17:9:31.651 DEBUG [main] select count(1) from (select * from tx_daoup_user)as _nutz_tmp
2016-7-12 17:9:31.659 DEBUG [main] SQLException
java.sql.SQLSyntaxErrorException: ORA-00933: SQL 命令未正确结束
> Fix: ORA-00933: SQL 命令未正确结束

- src/org/nutz/service/EntityService.java
还原注释的传Object的方法，项目在用这些方法了，别注释呀！
> 还原注释的传Object的方法

- src/org/nutz/dao/impl/EntityHolder.java
在 maker.make(classOfT); 方法中有
holder.set(en); // 保存一下，这样别的实体映射到这里时会用的到
因此此处不需要再put了
> map.put(classOfT, re); 这行重复多余了

- src/org/nutz/dao/impl/NutDao.java
final EntityOperator opt = _optBy(Lang.first(obj));
if (null == opt)
return null;
int size = Lang.length(obj);
if (size < 1)
return obj;
Object first = Lang.first(obj);
这里两个return是两个保护性校验。正常情况下执行
final EntityOperator opt = _optBy(Lang.first(obj));
int size = Lang.length(obj);
Object first = Lang.first(obj);
也就是说first通常会执行到，虽然 Lang.first(obj) 的成本并不高，
但是感觉调一次清爽些。
另外在 null != opt 时，
size 总是 >= 1的
> Lang.length(obj) 调一次清爽些

- src/org/nutz/lang/Lang.java
有如下使用场景：
`TagEntity.java`类定义
```java
public class TagEntity {
/** ID */
private long id;
/** 标签名称 */
@Column("name")
private String tagName;
// 省略getter、setter
}
```
自定义SQL的内容，由第三方提供只能 readonly
```sql
/* keyword.query */
SELECT
keyword_tag.id,
cc_tag.name
FROM
keyword_tag
LEFT JOIN
cc_tag
ON
keyword_tag.tag_id = cc_tag.id
WHERE
keyword_tag.keyword = @keyword
```
预想的调用代码
```java
Sql sql = nutDao.sqls().create("keyword.query");
sql.params().set("keyword", "我有只笔");
sql.setCallback(Sqls.callback.entities());
sql.setEntity(nutDao.getEntity(Record.class));
nutDao.execute(sql);
List<Record> list = sql.getList(Record.class);
return list.stream().map(re -> {return re.toPojo(TagEntity.class);}).collect(Collectors.toList());
```
结果就是`TagEntity`对象中的`tagName`属性没有值，因为现在`Record#toPojo`方法不支持`Column`注解里面写的 …
> 给 Lang#map2Object 添加该 Object 是否存在 Column 注解的判断方便进行赋值

- src/org/nutz/dao/impl/jdbc/h2/H2JdbcExpert.java
> 重写H2下获得表索引方法

- src/org/nutz/mvc/ActionInfo.java
- src/org/nutz/mvc/HttpAdaptor2.java
- src/org/nutz/mvc/adaptor/AbstractAdaptor.java
- src/org/nutz/mvc/adaptor/PairAdaptor.java
- src/org/nutz/mvc/adaptor/WhaleAdaptor.java
- src/org/nutz/mvc/impl/processor/AdaptorProcessor.java
- src/org/nutz/mvc/upload/UploadAdaptor.java
- test/org/nutz/mvc/testapp/adaptor/SimpleAdaptorTest.java
- test/org/nutz/mvc/testapp/classes/action/adaptor/AdaptorTestModule.java
Change: 
1. 入口方法的POJO参数不声明 Param 注解也可以注入，效果与 @Param("..") 保持一致
2. ActionInfo 增加 paramNames 属性，使 Processor 在初始化时可以获取参数名称数组
3. 新增 HttpAdaptor2 接口（继承自 HttpAdaptor ），提供更高级别的init方法
4. AbstractAdaptor 由实现 HttpAdaptor 接口调整为实现 HttpAdaptor2 接口
5. 当入口函数需要定义 AdaptorErrorContext 类型参数时，不再硬性要求定义为入口函数的最后一个参数，可以为入口函数中任意位置的参数（存在多个 AdaptorErrorContext 参数时只以第一个为准）
6. 增加上述调整相应的 test case
> HttpAdaptor 增强调整

- src/org/nutz/mvc/adaptor/AbstractAdaptor.java
- test/org/nutz/mvc/testapp/adaptor/SimpleAdaptorTest.java
- test/org/nutz/mvc/testapp/classes/action/adaptor/AdaptorTestModule.java
fix:
1. 入口函数存在多个 AdaptorErrorContext 参数的时候可能会出现路径参数对应错乱及没有以第一个 AdaptorErrorContext 参数为准的问题
chang:
2. 增加入口函数存在多个 AdaptorErrorContext 参数的 test case
> fix:入口函数存在多个 AdaptorErrorContext 参数的时候可能会出现路径参数对应错乱及没有以第一个 AdaptorErrorContext 参数为准的问题

- src/org/nutz/lang/reflect/FastMethodFactory.java
理论上修改这个
````
/**
* Returns the descriptor corresponding to the given method.
* 
* @param m
*            a {@link Method Method} object.
* @return the descriptor of the given method.
*/
public static String getMethodDescriptor(final Method m) {
Class<?>[] parameters = m.getParameterTypes();
StringBuilder buf = new StringBuilder();
buf.append('(');
for (int i = 0; i < parameters.length; ++i) {
getDescriptor(buf, parameters[i]);
}
buf.append(')');
getDescriptor(buf, m.getReturnType());
return buf.toString();
}
/**
* Returns the descriptor corresponding to the given method.
* 
* @param m
*            a {@link Method Method} object.
* @return the descriptor of the given method.
*/
public static String getMethodDescriptor(final Method m) {
Class<?>[] parameters = m.getParameterTypes(); …
```
> fix 存在不同ioc不同classloader 相同 bean name 被错误缓存的bug #1395

- src/org/nutz/dao/util/cri/Exps.java
- src/org/nutz/dao/util/cri/IntRange.java
- src/org/nutz/dao/util/cri/LongRange.java
- src/org/nutz/dao/util/cri/SqlExpressionGroup.java
- test/org/nutz/dao/texp/CndTest.java
`Criteria cri = Cnd.cri();`
`cri.where().andIn("id", 3,4,5).andIn("name", "Peter", "Wendal", "Juqkai");`
原来方法中只有
`andNotIn(String name, long... ids)`
等方法，增加了
`int[],long[],String[],List<Integer>,List<Long>,List<String>`
等参数，便于调用。
例如：
`    	List<String> ids = new ArrayList<String>();`
`    	ids.add("bj");`
`    	ids.add("sh");`
`    	ids.add("gz");`
`    	ids.add("sz");`
`    	Criteria cri = Cnd.cri();`
`    	cri.where().andNotInStrList("nm", ids);`
单元测试也增加了
> Criteria 接口中andIn方法和andNotIn增加int[],long[],String[],List<Integer>,List<Long>,List<String>参数

- src/org/nutz/dao/util/Daos.java
新建的count语句需要设置Entity信息才能正常解析原sql中的字段信息；
> queryCount时需要设置count语句的Entity信息；

- src/org/nutz/dao/impl/jdbc/AbstractJdbcExpert.java
This class is used to represent .  This method named 'wrap' is to wrap an sql string and return a sql statement. Thus, the method name 'createQuery' is more intuitive than 'wrap'.
> Change method name 'wrap' to 'createQuery'

- pom.xml
- test/org/nutz/json/JsonTest.java
Tests in `test/org/nutz/json/JsonTest.java` compares toJson results with several hard-coded strings. 
However, the `toJSON` function depends on `getDeclaredField` which does not guarantee any specific order, thus resulting a different serialized json string. So tests may fail or pass without any changes made to the source code and cannot serve as good regression tests.
This PR proposes to use JSONAssert and change test assertions to check JSON results in a safer way.
> Make test more stable by using JSONAssert equals

- doc/manual/dao/update_with_version.man
1.更新乐观锁最新语法
2.删除insert时version字段自动填0的描述（阅读源码后发现并没有该功能）
> 更新乐观锁最新语法，删除错误描述

- src/org/nutz/lang/util/NutMap.java
- test/org/nutz/lang/util/NutMapTest.java
> Fix issue #1563: NutMap attach 另外一个map之后，序列化成json时两个内容都会出来，不符合预期

- src/org/nutz/http/Cookie.java
- src/org/nutz/http/Response.java
> 为cookie添加更多关键字；Response header中Set-Cookie忽略大小写

- src/org/nutz/dao/impl/sql/run/NutDaoRunner.java
nutz dao 读写分离 有两个判断条件
1  select, 2 不是事务
第二个条件不是必要的。取消掉可以兼容pg
> fix 读写分离不支持pg数据库的问题

- pom.xml
- src/org/nutz/dao/impl/jdbc/mysql/MysqlJdbcExpert.java
- src/org/nutz/dao/impl/jdbc/mysql/MysqlJsonAdaptor.java
- src/org/nutz/dao/impl/jdbc/mysql/MysqlJsonCompactAdaptor.java
- src/org/nutz/dao/impl/jdbc/mysql/MysqlJsonTidyAdaptor.java
- src/org/nutz/dao/impl/jdbc/psql/PsqlJdbcExpert.java
- src/org/nutz/dao/impl/jdbc/psql/PsqlJsonAdaptor.java
- src/org/nutz/dao/impl/jdbc/psql/PsqlJsonCompactAdaptor.java
- src/org/nutz/dao/impl/jdbc/psql/PsqlJsonTidyAdaptor.java
- test/org/nutz/dao/test/normal/mysql/AllMysqlTest.java
- test/org/nutz/dao/test/normal/mysql/MysqlJsonAdaptorTest.java
- test/org/nutz/dao/test/normal/mysql/MysqlJsonAdaptorTestBean.java
- test/org/nutz/dao/test/normal/psql/AllPsqlTest.java
- test/org/nutz/dao/test/normal/psql/PsqlJsonAdaptorTest.java
- test/org/nutz/dao/test/normal/psql/PsqlJsonAdaptorTestBean.java
- test/tmpl.nutz-test.properties
默认的是使用 `JsonFormat.tidy()` 格式来进行数据保存，添加上可使用 `JsonFormat.compact()` 格式的方式来进行保存。
> 给Mysql跟Postgresql添加保存JSON内容时的设置格式的ValueAdaptor
