nutzam/nutz

src/org/nutz/dao/util/Daos.java

Daos 完善alter 根据注解添加 注释 默认值 同时支持动态表处理

---

test/org/nutz/dao/test/meta/DynamicTable.java
test/org/nutz/dao/test/normal/SimpleDaoTest.java

添加 动态表的 字段alter TestCase

---

src/org/nutz/dao/util/Daos.java

原来的缺少对分表的字段变化的检查 ，增加一个方法 对分表的字段变化也可以提示

添加一个 可以检查对分表的字段变化的检查方法

---

src/org/nutz/ioc/impl/PropertiesProxy.java
test/config/conf-utf8.properties
test/config/conf.properties
test/org/nutz/ioc/AllIoc.java
test/org/nutz/ioc/impl/PropertiesProxyTest.java

修改原`Properties`读取方式，使其支持`UTF-8`格式，及换行符，增加测试类

修改原properties读取方式

---

src/org/nutz/lang/Mirror.java
src/org/nutz/mvc/impl/Loadings.java
src/org/nutz/mvc/impl/NutLoading.java

fix issues 1002

---

src/org/nutz/dao/impl/sql/SqlLiteral.java
src/org/nutz/dao/impl/sql/SqlTemplate.java
src/org/nutz/el/opt/custom/Max.java
src/org/nutz/el/opt/custom/Min.java
src/org/nutz/mapl/impl/MaplMerge.java
src/org/nutz/mapl/impl/convert/ObjConvertImpl.java
src/org/nutz/mapl/impl/convert/StructureConvert.java
src/org/nutz/mvc/adaptor/injector/ObjectNaviNode.java

This pull request is focused on resolving occurrences of Sonar rule squid:S2325 - "private" methods that don't access instance data should be "static".
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2325
George Kankava

squid:S2325 - "private" methods that don't access instance data should be "static"

---

src/org/nutz/dao/Chain.java
src/org/nutz/dao/impl/sql/NutPojoMaker.java
src/org/nutz/el/opt/object/MethodOpt.java
src/org/nutz/img/Images.java
src/org/nutz/ioc/weaver/DefaultWeaver.java
src/org/nutz/lang/Mirror.java
src/org/nutz/lang/random/R.java
src/org/nutz/lang/socket/Sockets.java
src/org/nutz/mvc/adaptor/injector/ObjectNavlPairInjector.java
src/org/nutz/mvc/impl/NutActionChainMaker.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1488 - Local Variables should not be declared and then immediately returned or thrown.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1488
George Kankava

squid:S1488 - Local Variables should not be declared and then immediately returned or thrown

---

src/org/nutz/castor/Castors.java
src/org/nutz/dao/jdbc/Jdbcs.java
src/org/nutz/dao/util/cri/NameRange.java
src/org/nutz/dao/util/cri/NumberRange.java
src/org/nutz/dao/util/cri/OrderBySet.java
src/org/nutz/lang/reflect/AbstractFastClass.java
src/org/nutz/lang/reflect/FastClassAdpter.java
src/org/nutz/runner/NutRunner.java

This pull request is focused on resolving occurrences of Sonar rule squid:EmptyStatementUsageCheck - Empty statements should be removed.
https://dev.eclipse.org/sonar/coding_rules#q=squid:EmptyStatementUsageCheck
George Kankava

squid:EmptyStatementUsageCheck Empty statements should be removed

---

src/org/nutz/dao/impl/sql/NutStatement.java
src/org/nutz/dao/impl/sql/SqlFormat.java
src/org/nutz/dao/util/Daos.java

讨论见
[http://nutz.cn/yvr/t/tbpqdaos9ggqgod50a1epkognq](http://nutz.cn/yvr/t/tbpqdaos9ggqgod50a1epkognq)

修改Sql日志打印格式

---

src/org/nutz/repo/URLSafeBase64.java

添加一个 URLSafeBase64 的类进行 url safe 方式加密

---

src/org/nutz/dao/impl/sql/NutStatement.java
src/org/nutz/dao/impl/sql/SqlFormat.java

调整一下sql打印日志

---

src/org/nutz/service/EntityService.java

EntityService添加dao中传Object对象的方法，service做增删改查等操作，减少冗长代码，限制传的对象。

EntityService添加dao中传Object对象的方法

---

src/org/nutz/service/EntityService.java

修改两个query方法，不需传class参数，增加个不传参的query方法

修改两个query方法，不需传class参数，增加个不传参的query方法

---

src/org/nutz/lang/born/BorningException.java

Fix a typo from "becasue" to "because"

#fix a tiny typo 

---

src/org/nutz/json/AbstractJsonEntityFieldMaker.java
src/org/nutz/json/Json.java
src/org/nutz/json/JsonEntityFieldMaker.java
src/org/nutz/json/entity/JsonEntity.java
src/org/nutz/json/entity/JsonEntityField.java
src/org/nutz/json/impl/JsonEntityFieldMakerImpl.java
test/org/nutz/json/JsonEntityTest.java

问题见:  [这里](https://nutz.cn/yvr/t/v1jbf9v7c8h3hrm4ufnb530697)

add JsonEntityFieldMaker

---

src/org/nutz/dao/impl/jdbc/AbstractJdbcExpert.java
src/org/nutz/dao/util/Daos.java

在运行 Daos.migration 方法时添加是否对关键字进行逃逸处理的判断

---

src/org/nutz/ioc/java/ChainParsing.java
test/org/nutz/ioc/java/ChainParsingTest.java

ChainParsing支持解析 参数中继续调用方法或获取属性 的java表达式

issues #1264

---

src/org/nutz/dao/Dao.java
src/org/nutz/dao/impl/NutDao.java
test/org/nutz/dao/test/normal/SimpleDaoTest.java

在NutDao中增加@One获取到分页对象的方法
queryByJoin(Class<T> classOfT, String regex, Condition cnd, Pager pager)
在test/org/nutz/dao/test/normal/SimpleDaoTest.java中增加了测试数据和测试方法

在NutDao中增加@One获取到分页对象的方法

---

src/org/nutz/lang/Lang.java
src/org/nutz/lang/inject/InjectByField.java
src/org/nutz/lang/inject/InjectBySetter.java
src/org/nutz/lang/reflect/ReflectTool.java
src/org/nutz/mapl/impl/convert/ObjConvertImpl.java
test/org/nutz/castor/Map2UserTest.java
test/org/nutz/castor/model/BaseEntity.java
test/org/nutz/castor/model/BaseTreeEntity.java
test/org/nutz/castor/model/User.java

https://github.com/nutzam/nutz/issues/1288

修正map转对象和json转对象时泛型基类中泛型变量类型不正确问题。

---

src/org/nutz/dao/entity/annotation/Column.java
src/org/nutz/dao/entity/annotation/Table.java
src/org/nutz/dao/entity/annotation/View.java
src/org/nutz/dao/impl/entity/AnnotationEntityMaker.java
test/org/nutz/dao/test/entity/EntityParsingTest.java

给 @Table、@View、@Column 注解添加名称前缀后缀的功能

---

src/org/nutz/dao/Cnd.java

可能实现的不太好,或许不能合并吧....  o(*////▽////*)q

为Cnd类添加clone方法

---

src/org/nutz/mvc/Mvcs.java

Mvcs增加辅助函数直接取得国际化信息配合NutzCodeInsight实现国际化配置代码折叠提示

Mvcs增加辅助函数直接取得国际化信息配合NutzCodeInsight实现国际化配置代码折叠提示

---

src/org/nutz/mvc/MvcI18n.java
src/org/nutz/mvc/Mvcs.java

增加web环境下 国际化 相关帮助函数

---

src/org/nutz/json/AbstractJsonEntityFieldMaker.java
src/org/nutz/lang/Mirror.java
test/org/nutz/json/JsonTest.java

fix #1393 增加测试用例 JsonTest.test_final_field 并修改代码通过了测试

---

src/org/nutz/mvc/impl/NutLoading.java

这里逻辑应该是这样的吧,不然
`
@IocBean(name = "$setup_demo")
`
拿不到setup

change: 从ioc中获取setup实例逻辑问题

---

src/org/nutz/http/Http.java

增加 可定义请求方法
GET, POST, OPTIONS, PUT, DELETE, TRACE, CONNECT, HEAD

增加 可定义请求方法

---

doc/manual/json/mvc.man

mvc @Ok中的json 文档完善

---

src/org/nutz/ioc/loader/annotation/AnnotationIocLoader.java

setter方法上使用@Inject和@IocBean(fields="")都支持optional设置

使得AnnotationIocLoader能够更好的支持optional的设置

---

src/org/nutz/ioc/loader/annotation/AnnotationIocLoader.java

补充：基本形式也支持optional设置

---

src/org/nutz/resource/Scans.java

修改Scans类的Javadoc与错误提示信息描述

---

src/org/nutz/img/Colors.java
src/org/nutz/lang/util/Tag.java

在使用正则表达式时，利用好其预编译功能，可以有效加快正则匹配速度。

在使用正则表达式时，利用好其预编译功能，可以有效加快正则匹配速度。

---

src/org/nutz/castor/castor/String2Number.java
src/org/nutz/conf/NutConf.java
src/org/nutz/el/parse/IdentifierParse.java
src/org/nutz/http/Cookie.java
src/org/nutz/ioc/java/ChainParsing.java
src/org/nutz/ioc/loader/annotation/AnnotationIocLoader.java
src/org/nutz/ioc/loader/properties/PropertiesIocLoader.java
src/org/nutz/json/handler/JsonNumberHandler.java
src/org/nutz/lang/Times.java
src/org/nutz/mapl/impl/convert/StructureConvert.java

add:翻转equals方法;避免空指针异常

---

src/org/nutz/dao/entity/Record.java
src/org/nutz/dao/impl/entity/EntityObjectContext.java
src/org/nutz/dao/impl/sql/SqlFormat.java
src/org/nutz/dao/impl/sql/SqlLiteral.java
src/org/nutz/json/JsonFormat.java
src/org/nutz/lang/meta/Email.java
src/org/nutz/lang/segment/CharSegment.java
src/org/nutz/lang/segment/SegmentNode.java
src/org/nutz/lang/util/SimpleContext.java
src/org/nutz/mvc/upload/UploadInfo.java
src/org/nutz/mvc/view/HttpEnhanceResponse.java

This non-final class defines a clone() method that does not call super.clone(). If this class ("A") is extended by a subclass ("B"), and the subclass B calls super.clone(), then it is likely that B's clone() method will return an object of type A, which violates the standard contract for clone().
If all clone() methods call super.clone(), then they are guaranteed to use Object.clone(), which always returns an object of the correct type.

update:clone method does not call super.clone()

---

src/org/nutz/lang/Nums.java

This code converts an int value to a float precision floating point number and then passing the result to the Math.round() function, which returns the int/long closest to the argument. This operation should always be a no-op, since the converting an integer to a float should give a number with no fractional part. It is likely that the operation that generated the value to be passed to Math.round was intended to be performed using floating point arithmetic

update:int value cast to float and then passed to Math.round

---

src/org/nutz/dao/entity/Record.java
src/org/nutz/dao/impl/entity/EntityObjectContext.java
src/org/nutz/dao/impl/sql/SqlFormat.java
src/org/nutz/dao/impl/sql/SqlLiteral.java
src/org/nutz/json/JsonFormat.java
src/org/nutz/lang/meta/Email.java
src/org/nutz/lang/segment/CharSegment.java
src/org/nutz/lang/segment/SegmentNode.java
src/org/nutz/lang/util/SimpleContext.java
src/org/nutz/mvc/upload/UploadInfo.java
src/org/nutz/mvc/view/HttpEnhanceResponse.java

Revert "update:clone method does not call super.clone()"

---

src/org/nutz/lang/Nums.java

Revert "update:int value cast to float and then passed to Math.round"

---

src/org/nutz/lang/util/SimpleContext.java
src/org/nutz/mvc/ActionContext.java
src/org/nutz/mvc/ActionInfo.java
src/org/nutz/mvc/RequestMatcher.java
src/org/nutz/mvc/annotation/ApiVersion.java
src/org/nutz/mvc/impl/ActionInvoker.java
src/org/nutz/mvc/impl/UrlMappingImpl.java
src/org/nutz/mvc/impl/reqmatcher/ApiVersionRequestMatcher.java
src/org/nutz/mvc/impl/reqmatcher/DefaultRequestMatcher.java
test/org/nutz/mvc/testapp/classes/action/mapping/Issue1530MappingAction.java
test/org/nutz/mvc/testapp/mapping/AllMapping.java
test/org/nutz/mvc/testapp/mapping/Issue1530MappingTest.java

改造UrlMappingImpl和ActionInvoker的实现, 添加一个注解和一个接口
```java
@Ok("raw")
@At("/mapping/issue1530/{version}")
@ApiVersion
public class Issue1530MappingAction {
@ApiVersion("v1")
@At("/yourname")
public String getYourName() {
return "v1";
}
@ApiVersion("v2")
@At("/yourname")
public String getYourName2() {
return "v2";
}
}
```

fix: issue 1530 添加@ApiVersion注解,实验性

---

pom.xml
src/org/nutz/dao/Cnd.java
src/org/nutz/dao/sql/GroupBy.java
src/org/nutz/dao/sql/OrderBy.java
src/org/nutz/dao/util/cri/AbstractSqlExpression.java
src/org/nutz/dao/util/cri/BetweenExpression.java
src/org/nutz/dao/util/cri/Exps.java
src/org/nutz/dao/util/cri/GroupBySet.java
src/org/nutz/dao/util/cri/IsNull.java
src/org/nutz/dao/util/cri/Like.java
src/org/nutz/dao/util/cri/NameRange.java
src/org/nutz/dao/util/cri/NestExps.java
src/org/nutz/dao/util/cri/NestingExpression.java
src/org/nutz/dao/util/cri/NoParamsSqlExpression.java
src/org/nutz/dao/util/cri/NumberRange.java
src/org/nutz/dao/util/cri/OrderByItem.java
src/org/nutz/dao/util/cri/OrderBySet.java
src/org/nutz/dao/util/cri/SimpleCriteria.java
src/org/nutz/dao/util/cri/SimpleExpression.java
src/org/nutz/dao/util/cri/SqlExpressionGroup.java
src/org/nutz/dao/util/cri/SqlRange.java
src/org/nutz/dao/util/cri/SqlValueRange.java
src/org/nutz/dao/util/lambda/LambdaQuery.java
src/org/nutz/dao/util/lambda/PFun.java
test/org/nutz/dao/AllDao.java
test/org/nutz/dao/texp/LamdaCndTest.java
test/org/nutz/dao/texp/Worker.java

实现使用lamda表达式生成查询条件，test case：[org.nutz.dao.texp.LamdaCndTest](https://github.com/nutzam/nutz/blob/feat-lamda-query/test/org/nutz/dao/texp/LamdaCndTest.java)

Feat lamda query

---

src/org/nutz/dao/util/Daos.java
src/org/nutz/dao/util/tables/TablesFilter.java
src/org/nutz/mvc/CommandLineRunner.java
src/org/nutz/mvc/impl/NutLoading.java
test/org/nutz/mvc/init/module/MvcCommandLineRunner.java

添加类似spring boot 中的 CommandLineRunner，用于应用启动后立即执行一些事情

Feat command line runner
